import { describe, it, expect } from 'vitest'
import { deriveTenGod } from '../../saju-engine/calculators/ten-gods'
import { stemByIndex } from '../../saju-engine/constants/stems'

// Day Master shorthand: index 0=갑(목양), 1=을(목음), 2=병(화양), 3=정(화음)
// 4=무(토양), 5=기(토음), 6=경(금양), 7=신(금음), 8=임(수양), 9=계(수음)

describe('Ten Gods derivation (십성)', () => {
  const dm = stemByIndex  // alias

  describe('비견 & 겁재 (same element)', () => {
    it('甲 DM + 甲 target = 비견', () => {
      expect(deriveTenGod(dm(0), dm(0))).toBe('비견')
    })
    it('甲 DM + 乙 target = 겁재', () => {
      expect(deriveTenGod(dm(0), dm(1))).toBe('겁재')
    })
    it('壬 DM + 壬 target = 비견', () => {
      expect(deriveTenGod(dm(8), dm(8))).toBe('비견')
    })
    it('壬 DM + 癸 target = 겁재', () => {
      expect(deriveTenGod(dm(8), dm(9))).toBe('겁재')
    })
  })

  describe('식신 & 상관 (DM generates)', () => {
    // 甲(wood) generates 丙(fire yang) → 식신 (same yang polarity)
    it('甲 DM + 丙 target = 식신', () => {
      expect(deriveTenGod(dm(0), dm(2))).toBe('식신')
    })
    // 甲(wood yang) generates 丁(fire yin) → 상관 (diff polarity)
    it('甲 DM + 丁 target = 상관', () => {
      expect(deriveTenGod(dm(0), dm(3))).toBe('상관')
    })
    // 壬(water yang) generates 甲(wood yang) → 식신
    it('壬 DM + 甲 target = 식신', () => {
      expect(deriveTenGod(dm(8), dm(0))).toBe('식신')
    })
    // 壬(water yang) generates 乙(wood yin) → 상관
    it('壬 DM + 乙 target = 상관', () => {
      expect(deriveTenGod(dm(8), dm(1))).toBe('상관')
    })
  })

  describe('편재 & 정재 (DM controls)', () => {
    // 甲(wood) controls 戊(earth yang) → 편재 (same yang)
    it('甲 DM + 戊 target = 편재', () => {
      expect(deriveTenGod(dm(0), dm(4))).toBe('편재')
    })
    // 甲(wood yang) controls 己(earth yin) → 정재
    it('甲 DM + 己 target = 정재', () => {
      expect(deriveTenGod(dm(0), dm(5))).toBe('정재')
    })
  })

  describe('편관 & 정관 (controls DM)', () => {
    // 甲(wood yang) is controlled by 庚(metal yang) → 편관
    it('甲 DM + 庚 target = 편관', () => {
      expect(deriveTenGod(dm(0), dm(6))).toBe('편관')
    })
    // 甲(wood yang) is controlled by 辛(metal yin) → 정관
    it('甲 DM + 辛 target = 정관', () => {
      expect(deriveTenGod(dm(0), dm(7))).toBe('정관')
    })
  })

  describe('편인 & 정인 (generates DM)', () => {
    // 甲(wood yang) is generated by 壬(water yang) → 편인 (same yang)
    it('甲 DM + 壬 target = 편인', () => {
      expect(deriveTenGod(dm(0), dm(8))).toBe('편인')
    })
    // 甲(wood yang) is generated by 癸(water yin) → 정인
    it('甲 DM + 癸 target = 정인', () => {
      expect(deriveTenGod(dm(0), dm(9))).toBe('정인')
    })
  })

  describe('All 10 combinations from 壬(임수) Day Master', () => {
    const dmWater = dm(8)  // 壬 = water yang
    it('壬+壬 = 비견',  () => expect(deriveTenGod(dmWater, dm(8))).toBe('비견'))
    it('壬+癸 = 겁재',  () => expect(deriveTenGod(dmWater, dm(9))).toBe('겁재'))
    it('壬+甲 = 식신',  () => expect(deriveTenGod(dmWater, dm(0))).toBe('식신'))
    it('壬+乙 = 상관',  () => expect(deriveTenGod(dmWater, dm(1))).toBe('상관'))
    it('壬+丙 = 편재',  () => expect(deriveTenGod(dmWater, dm(2))).toBe('편재'))
    it('壬+丁 = 정재',  () => expect(deriveTenGod(dmWater, dm(3))).toBe('정재'))
    it('壬+戊 = 편관',  () => expect(deriveTenGod(dmWater, dm(4))).toBe('편관'))
    it('壬+己 = 정관',  () => expect(deriveTenGod(dmWater, dm(5))).toBe('정관'))
    it('壬+庚 = 편인',  () => expect(deriveTenGod(dmWater, dm(6))).toBe('편인'))
    it('壬+辛 = 정인',  () => expect(deriveTenGod(dmWater, dm(7))).toBe('정인'))
  })
})
